<a href="https://colab.research.google.com/github/Error-Nasim/Simulation-and-Modeling-Lab/blob/main/Assignments/SIM_CP1_AbuNasim_0432320005101033.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
from sympy import Matrix
import matplotlib.pyplot as plt
import seaborn as sns

# **1: Advanced Scalar & Array Operations**

In [3]:
scalar = 3.7
arr = np.array([5.5, 8.5, 9.5, 3.5, 1.5, 4.5, 5.5, 6.5])

# addition
print(f"addition: {scalar + arr}")
# subtraction
print(f"subtraction: {scalar - arr}")
# multiplication
print(f"multiplication: {scalar * arr}")
# division
print(f"division: {scalar / arr}")
#power
print(f"power: {scalar ** arr}")

#squar root
print(f"squart root: {np.sqrt(arr)}")
#exponential
print(f"exponential: {np.exp(arr)}")
#natural logarithm
print(f"natural logarithm: {np.log(arr)}")
#log base 10
print(f"log base 10: {np.log10(arr)}")

#sin
print(f"sin: {np.sin(arr)}")
#cos
print(f"cos: {np.cos(arr)}")
#tan
print(f"tan: {np.tan(arr)}")
#arcsin
clip_arr=np.clip(arr,-1,1)
print(f"arcsin: {np.arcsin(clip_arr)}")
#arccos
print(f"arccos: {np.arccos(clip_arr)}")


# **2. Matrix Mathematical Operations**

In [14]:
matrix=np.array([
    [1.5, -2.7, 3.1],
    [4.0, 5.8, -0.9],
    [6.2, 7.4, 0.1],
    [-0.5, 1.2, 8.8]
])
#sin
print(f"sin: {np.sin(matrix)}")
#cos
print(f"cos: {np.cos(matrix)}")
#tan
print(f"tan: {np.tan(matrix)}")
#arcos
print(f"arccos: {np.arccos(matrix)}")
#arcsin
print(f"arcsin: {np.arcsin(matrix)}")
#arctan
print(f"arctan: {np.arctan(matrix)}")

#exp
print(f"exp: {np.exp(matrix)}")
#log
print(f"log: {np.log(matrix)}")
#log10
print(f"log10: {np.log10(matrix)}")

#absulute value
print(f"absulute value: {np.abs(matrix)}")
#squar root
print(f"squar root: {np.sqrt(matrix)}")
#squar
print(f"squar: {np.square(matrix)}")
#cube root
print(f"cube root: {np.cbrt(matrix)}")

#reminder when div by 3
print(f"reminder when div by 3: {np.remainder(matrix,3)}")
#round
print(f"round: {np.round(matrix)}")
#ceil
print(f"ceil: {np.ceil(matrix)}")
#floor
print(f"floor: {np.floor(matrix)}")


sin: [[ 0.99749499 -0.42737988  0.04158066]
 [-0.7568025  -0.46460218 -0.78332691]
 [-0.0830894   0.8987081   0.09983342]
 [-0.47942554  0.93203909  0.58491719]]
cos: [[ 0.0707372  -0.90407214 -0.99913515]
 [-0.65364362  0.88551952  0.62160997]
 [ 0.9965421   0.43854733  0.99500417]
 [ 0.87758256  0.36235775 -0.81109301]]
tan: [[14.10141995  0.47272763 -0.04161665]
 [ 1.15782128 -0.52466622 -1.26015822]
 [-0.08337771  2.04928417  0.10033467]
 [-0.54630249  2.57215162 -0.72114688]]
arccos: [[       nan        nan        nan]
 [       nan        nan 2.69056584]
 [       nan        nan 1.47062891]
 [2.0943951         nan        nan]]
arcsin: [[        nan         nan         nan]
 [        nan         nan -1.11976951]
 [        nan         nan  0.10016742]
 [-0.52359878         nan         nan]]
arctan: [[ 0.98279372 -1.21609067  1.25875421]
 [ 1.32581766  1.40006112 -0.7328151 ]
 [ 1.4108832   1.43647488  0.09966865]
 [-0.46364761  0.87605805  1.45764535]]
exp: [[4.48168907e+00 6.7205512

/tmp/ipykernel_1139/1834346385.py:14: RuntimeWarning: invalid value encountered in arccos
  print(f"arccos: {np.arccos(matrix)}")
/tmp/ipykernel_1139/1834346385.py:16: RuntimeWarning: invalid value encountered in arcsin
  print(f"arcsin: {np.arcsin(matrix)}")
/tmp/ipykernel_1139/1834346385.py:23: RuntimeWarning: invalid value encountered in log
  print(f"log: {np.log(matrix)}")
/tmp/ipykernel_1139/1834346385.py:25: RuntimeWarning: invalid value encountered in log10
  print(f"log10: {np.log10(matrix)}")
/tmp/ipykernel_1139/1834346385.py:30: RuntimeWarning: invalid value encountered in sqrt
  print(f"squar root: {np.sqrt(matrix)}")


# **3. Matrix Statistics and Analysis**

In [12]:
mat_34 = np.random.uniform(-10, 10, (3, 4))
#max value
print(f"max value: {np.max(mat_34)}")
#min value
print(f"min value: {np.min(mat_34)}")
#index position
print(f"index position: {np.argmax(mat_34)}")
#index position
print(f"index position: {np.argmin(mat_34)}")
#sum of all elements
print(f"sum of all elements: {np.sum(mat_34)}")
#mean of all elements
print(f"mean of all elements: {np.mean(mat_34)}")
#product of all elements
print(f"product of all elements: {np.prod(mat_34)}")
#standard deviation
print(f"standard deviation: {np.std(mat_34)}")
#median
print(f"median: {np.median(mat_34)}")
#variance
print(f"variance: {np.var(mat_34)}")

#sum of each row
print(f"sum of each row: {np.sum(mat_34, axis=0)}")
#sum of each column
print(f"sum of each column: {np.sum(mat_34, axis=1)}")
#max value from each row
print(f"max value from each row: {np.max(mat_34, axis=0)}")
#min value from each col
print(f"min value from each col: {np.min(mat_34, axis=1)}")
#

max value: 8.946277955597608
min value: -9.441799720012916
index position: 7
index position: 2
sum of all elements: 15.732210911937234
mean of all elements: 1.3110175759947695
product of all elements: -225392982.66022497
standard deviation: 6.938221500356713
median: 4.934497021291485
variance: 48.13891758801216
sum of each row: [ 18.1785491    1.61688675 -11.74379748   7.68057254]
sum of each column: [-18.88837594  26.80347939   7.81710746]
max value from each row: [8.30955506 6.39390114 5.92790003 8.94627796]
min value from each col: [-9.44179972  5.53540026 -8.22989779]


# **4. Matrix Sorting and Searching Operations**

In [13]:
mat_44 = np.random.randint(-20, 20, (4, 4))

#sort each row in asc order
print(f"sort each row in asc order: {np.sort(mat_44, axis=0)}")
#sort each row in dec order
print(f"sort each row in dec order: {np.sort(mat_44, axis=0)[::-1]}")
#sort mat in asc order
print(f"sort mat in asc order: {np.sort(mat_44)}")
#sort mat in dec order
print(f"sort mat in dec order: {np.sort(mat_44)[::-1]}")


#five largest value in mat
print(f"five largest value in mat: {np.partition(mat_44.flatten(), -5)[-5:]}")
#five smallest value in mat
print(f"five smallest value in mat: {np.partition(mat_44.flatten(), 5)[:5]}")
#Positions of elements greater than the matrix mean
print(f"Positions of elements greater than the matrix mean: {np.where(mat_44 > np.mean(mat_44))}")
#cnt of pos val
print(f"cnt of pos val: {np.count_nonzero(mat_44 > 0)}")
#cnt of neg val
print(f"cnt of neg val: {np.count_nonzero(mat_44 < 0)}")
#cnt of zero val
print(f"cnt of zero val: {np.count_nonzero(mat_44 == 0)}")
#

sort each row in asc order: [[-20 -16 -15 -14]
 [ -2  -6  -9  -3]
 [  2   8  -1   9]
 [  9  11  14  13]]
sort each row in dec order: [[  9  11  14  13]
 [  2   8  -1   9]
 [ -2  -6  -9  -3]
 [-20 -16 -15 -14]]
sort mat in asc order: [[-15 -14  -2  11]
 [ -9   8   9   9]
 [-20 -16  13  14]
 [ -6  -3  -1   2]]
sort mat in dec order: [[ -6  -3  -1   2]
 [-20 -16  13  14]
 [ -9   8   9   9]
 [-15 -14  -2  11]]
five largest value in mat: [ 9  9 11 13 14]
five smallest value in mat: [-20 -16 -15 -14  -9]
Positions of elements greater than the matrix mean: (array([0, 1, 1, 1, 2, 2, 3, 3]), array([1, 0, 1, 3, 2, 3, 0, 2]))
cnt of pos val: 7
cnt of neg val: 9
cnt of zero val: 0
