<a href="https://colab.research.google.com/github/Error-Nasim/Simulation-and-Modeling-Lab/blob/main/Assignments/SIM_Lab2_Abu_Nasim_0432320005101033.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
from sympy import Matrix
import matplotlib.pyplot as plt
import seaborn as sns

# ***Task 1***

In [5]:

# Input the last two digits of your student ID
d1 = int(input("Enter the last digit of your student ID (d1): "))
d2 = int(input("Enter the second last digit of your student ID (d2): "))

# Create the matrix
A = np.array([
    [d1 + 2, d2 + 1],
    [2 * d1, d2 + 2]
])

# Display the matrix
print("\nMatrix A:")
print(A)

Enter the last digit of your student ID (d1): 3
Enter the second last digit of your student ID (d2): 3

Matrix A:
[[5 4]
 [6 5]]


# ***Task 2***

In [6]:
# Example matrix A
A = np.array([[3, 1], [2, 2]])

# 1. Shape of a matrix
size_A = A.shape  # Returns dimensions (rows, columns)


# 2. Determinant of a matrix
det_A = np.linalg.det(A)  # Returns the determinant of the matrix

# 3. Rank of a matrix
rank_A = np.linalg.matrix_rank(A)  # Returns the rank of the matrix

# 4. Inverse of a matrix
if np.linalg.det(A) != 0:  # Check if matrix is invertible
    inv_A = np.linalg.inv(A)  # Compute the inverse of A
else:
    inv_A = "Matrix is singular, cannot compute inverse"  # No inverse if determinant is 0


# 5. Eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)  # Compute eigenvalues and eigenvectors



# Display results
print("Shape of A:", size_A)
print("Determinant of A:", det_A)
print("Inverse of A:\n", inv_A)
print("Rank of A:", rank_A)

print("Eigenvalues of A:", eigenvalues)
print("Eigenvectors of A:\n", eigenvectors)



Shape of A: (2, 2)
Determinant of A: 4.000000000000001
Inverse of A:
 [[ 0.5  -0.25]
 [-0.5   0.75]]
Rank of A: 2
Eigenvalues of A: [4. 1.]
Eigenvectors of A:
 [[ 0.70710678 -0.4472136 ]
 [ 0.70710678  0.89442719]]


# Task **3**

In [7]:
B = A.copy()

# Changing exactly one value: Adding +1 to row 1, col 1 (A[0, 0])
row_idx, col_idx = 0, 0
B[row_idx, col_idx] += 1


print(
    f"Changed Element: Row {row_idx + 1}, Column {col_idx + 1} "
    f"(Value changed from {A[row_idx, col_idx]} to {B[row_idx, col_idx]})"
)
print("Matrix B =\n", B)

Changed Element: Row 1, Column 1 (Value changed from 3 to 4)
Matrix B =
 [[4 1]
 [2 2]]


# **Task 4**

In [8]:
# Example matrix A
A = np.array([[4, 1], [2, 2]])

# 1. Shape of a matrix
size_A = A.shape  # Returns dimensions (rows, columns)


# 2. Determinant of a matrix
det_A = np.linalg.det(A)  # Returns the determinant of the matrix

# 3. Rank of a matrix
rank_A = np.linalg.matrix_rank(A)  # Returns the rank of the matrix

# 4. Inverse of a matrix
if np.linalg.det(A) != 0:  # Check if matrix is invertible
    inv_A = np.linalg.inv(A)  # Compute the inverse of A
else:
    inv_A = "Matrix is singular, cannot compute inverse"  # No inverse if determinant is 0


# 5. Eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)  # Compute eigenvalues and eigenvectors



# Display results
print("Shape of A:", size_A)
print("Determinant of A:", det_A)
print("Inverse of A:\n", inv_A)
print("Rank of A:", rank_A)

print("Eigenvalues of A:", eigenvalues)
print("Eigenvectors of A:\n", eigenvectors)

Shape of A: (2, 2)
Determinant of A: 6.0
Inverse of A:
 [[ 0.33333333 -0.16666667]
 [-0.33333333  0.66666667]]
Rank of A: 2
Eigenvalues of A: [4.73205081 1.26794919]
Eigenvectors of A:
 [[ 0.80689822 -0.34372377]
 [ 0.59069049  0.9390708 ]]


# Task 5

Here are the simplified answers for **Question 5 (Comparison & Explanation)**:

### **Question 1: How did the determinant change and why?**

*   **Answer:**
    When one number in the original Matrix A was changed to make Matrix B, its determinant  also changed. For example, if Matrix A had a determinant of `4.0` and we changed a number, Matrix B's determinant might become `6.0`. It could go up, go down, or even become zero.

*   **Why:**
    The determinant is like a unique identifier for a matrix. Every number in the matrix contributes to its determinant. When you change even just one number, the overall calculation for the determinant changes. Think of it like a recipe: if you change one ingredient, the determinant will be different.


### **Question 2: Did the rank change? Explain.**

*   **Answer:**
    The rank of the matrix *might have changed, or it might have stayed the same*.
    *   If the determinants of both Matrix A and Matrix B were not zero, then the rank **did not change** (it remained 2 for our `2x2` matrices).
    *   If Matrix A's determinant was not zero, but Matrix B's determinant *became* zero, then the rank **decreased** from 2 to 1.

*   **Explanation:**
    The rank of a matrix tells us how 'independent' its rows or columns are. For our `2x2` matrices, a rank of 2 means the rows/columns are truly independent. If the determinant becomes zero, it means the rows or columns are no longer fully independent; one row can be created by multiplying the other. So, if changing a number makes the determinant zero, it means the matrix lost some of its 'independence', and its rank drops.


### **Question 3: How did the eigenvalues respond to the value change?**

*   **Answer:**
    The eigenvalues  generally shifted. If we changed a number directly on the main diagonal of the matrix (from top-left to bottom-right), the *sum* of the eigenvalues changed by the exact same amount we added or subtracted. If we changed a number off the diagonal, the eigenvalues still changed, but not in such a simple, direct way for their sum.

*   **Explanation:**
    Eigenvalues are Related to the 'behavior' of the matrix when it transforms vectors. There's a rule that the **sum of all eigenvalues** is equal to the **trace** of the matrix . So, if you add `+1` to a number on the main diagonal, the trace increases by `+1`, and therefore the sum of the eigenvalues also increases by `+1`. Changing an off-diagonal number makes the calculations for eigenvalues more complex, so the change isn't as straightforward.


### **Question 4: Is B easier or harder to invert than A? Why?**

*   **Answer:**
    *   **If the determinant of Matrix B is 0**: Matrix B is **impossible to invert**. You can't find its inverse at all.
    *   **If the determinant of Matrix B is not 0**: To see if B is 'easier' or 'harder' to invert than A, we look at something called its **condition number**. A smaller condition number means it's 'easier' or more reliable to invert.
        *   If Matrix B's condition number is smaller than Matrix A's, then B is numerically **easier** to invert.
        *   If Matrix B's condition number is larger than Matrix A's, then B is numerically **harder** to invert.

*   **Why:**
    Inverting a matrix means finding another matrix that, when multiplied, gives you the identity matrix. If a matrix has a determinant very close to zero, or a very high **condition number**, it means it's 'wobbly' or very sensitive. Even tiny errors during computer calculations can lead to big mistakes in the inverted matrix. So, an 'ill-conditioned' matrix is 'harder' to invert accurately and reliably because it's prone to these errors.